### PR TITLE
Add support for host checking

### PR DESCRIPTION
**Pull request by kmlucy**
Linked to https://github.com/butlerx/wetty/pull/250

### CODE REVIEW

**Comment by svenihoney** [comment]
Please add a description/documentation to the README.md to allow users to see the option in the docs.

**Comment by svenihoney** [comment]
Also, this could only be merged if butlerx/wetty#250 is merged. Beforehand the `Dockerfile` has to be adapted, too.

**Comment by kmlucy** [comment]
README is updated. I know this has to wait until the upstream PR is merged, but hopefully that will be soon.

What am I missing with the Dockerfile? I believe as soon as the upstream PR is merged, no changed should be needed there.

**Comment by svenihoney** [comment]
In the Dockerfile, the tag 1.3.0 is explicitly requested: `git clone https://github.com/butlerx/wetty --branch v1.3.0`. If the PR for wetty is accepted, this would have to be changed.

**Comment by kmlucy** [comment]
I'm following now. Yes, that would need to change. Once the PR is accepted and a new tag created, I can update the Dockerfile in this PR.

**Comment by kmlucy** [comment]
@svenihoney What do you think about getting rid of the tag and just pulling the latest?
```
git clone https://github.com/butlerx/wetty /app
```

**Comment by svenihoney** [comment]
I don't like to do this, since then the version of the docker container on docker hub can't be reproduced - the wetty version in the container simply depends on the point in time the container has been created and not on a well defined version.

My approach would be: If the wetty patch has been accepted, let the wetty team release a new version (by setting a tag) and then we update the tag in the docker container.

**Comment by kmlucy** [comment]
How about this approach of checking out a specific commit? The problem with the tags is that they don't seem to be being updated. There has only been one in the past year on this project. With commit SHAs, you can update it whenever you want, but it is still pinned to a specific point in time.

**Pull request merged**
