### PR TITLE
added env variable WETTY_PORT to allow running on different port

### PR DESCRIPTION
**Pull request by apnar**

### CODE REVIEW

**Comment by svenihoney** [comment]
What is the reason behind this? It is not a good idea to change the port since it is marked as exposed by `EXPOSE 3000`...

**Comment by apnar** [comment]
Was a pretty narrow corner case where I had a port conflict within the name space.  I doubt too many others would ever need it, but figured it was better to shoot over a PR than not.  Feel free to ignore if you don't think it'll be useful to anyone else.

**Comment by svenihoney** [comment]
I just want to understand: How can you have a port conflict in a docker container?

**Comment by apnar** [comment]
Was in a k8s pod where multiple containers share a common name space (and this can conflict ports), really corner case for an app like this :)

**Pull request merged**
